### ISSUE TITLE
Encodes high code points multiple times

### ISSUE THREAD

**Issue by LinusU** [mhzed/utf8-encoder#1]
Some code says more than a thousand words 😄 

https://runkit.com/embed/4nw56f87o3fm

I think that the problem is that you are missing to increase the index when reading a code point that is to big to fit inside a single utf-16 code. Thus running `codePointAt` at the second part of the surrogate pair as well...

**Comment by mhzed** [comment]
Yikes, awful bug.  Thanks for reporting, should be fixed now.
